run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor

linters-settings:
  goimports:
    local-prefixes: ulascansenturk/service
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
    ignore-words:
      - instalment
      - instalments
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - unnamedResult
  dupl:
    threshold: 800
  gomnd:
    ignored-files:
      - 'workflows'
      - 'injector.go'
      - 'db_setup.go'
  exhaustive:
    default-signifies-exhaustive: true
    default-case-required: true

linters:
  disable-all: true
  enable:
    - dupl
    - exhaustive
    - exportloopref
    - gas
    - gochecknoinits
    - gocritic
    - godot
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - nonamedreturns
    - prealloc
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wsl
  fast: false

issues:
  exclude-rules:
    - text: "GetQueueUrl"
      linters:
        - stylecheck
    - text: "organisation"
      linters:
        - misspell
    - path: "internal/providers/payforce/factories.go"
      linters:
        - gomnd
        - misspell
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
    - path: internal/accounts/find_all.go
      linters:
        - gomnd
    - path: internal/appbase/mocks/mock_statsd.go
      linters:
        - gocritic
    - path: internal/temporalworkflows/cards/workflows/card_tokenization_test.go
      linters:
        - gocritic
        - wsl
    - text: "struct literal uses unkeyed fields"
      linters:
        - govet
