# Path to coverprofile file (output of `go test -coverprofile` command)
profile: cover.out

# (optional)
# When specified reported file paths will not contain local prefix in the output
local-prefix: "ulascansenturk/service"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0)
  # The minimum coverage that each file should have
  file: 0

  # (optional; default 0)
  # The minimum coverage that each package should have
  package: 80

  # (optional; default 0)
  # The minimum total coverage project should have
  total: 80

# Holds regexp rules which will exclude matched files or packages from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - ^internal/accounts
    - ^internal/admintasks
    - ^internal/api/routes.go
    - ^internal/api/server
    - ^internal/basaccounts
    - ^internal/cache
    - ^internal/constants
    - ^internal/events
    - ^internal/providers/instafin
    - ^internal/shared
    - ^internal/temporalworkflows/admintasks/workflows
    - ^internal/temporalworkflows/shared/utils
    - ^internal/temporalworkflows/cards/workflows
    - ^internal/transactions
    - ^internal/ledgersync

override:
  # Temporary solution to bypass the coverage for the internal/api/v2 package
  - threshold: 10
    path: ^internal/api/v2
