version: "3.9"
services:
  app:
    build:
      context: .
      target: dev
    entrypoint: ["go", "run", "./cmd/server"]
    init: true
    environment:
      DATABASE_HOST: database
      DATABASE_HOST_RO: database
      DATABASE_NAME: service
      DATABASE_PASSWORD: service-password
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      REDIS_ENDPOINT: redis
      REDIS_PORT: 6379
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      TEMPORAL_ADDRESS: temporal:7233
      TC_HOST: host.docker.internal
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  temporal:
    build: https://github.com/temporalio/temporalite.git#main
    ports:
      - "7233:7233"
      - "8233:8233"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8233/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  database:
    image: public.ecr.aws/docker/library/postgres:13.3
    environment:
      POSTGRES_DB: service
      POSTGRES_PASSWORD: service-password
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
