apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.13.1
        ports:
        - containerPort: 7233
        readinessProbe:
          httpGet:
            path: /health
            port: 8233
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: myapp-namespace
spec:
  ports:
  - port: 7233
    targetPort: 7233
  selector:
    app: temporal

